### ISSUE TITLE
Magento 2 Synerise Integration Error on Product Wishlist Remove

### ISSUE THREAD

**Issue by WiktorDziadosz** [Synerise/magento2-integration#83]
A TypeError occurs in the Synerise\Integration\SyneriseApi\Mapper\Event\WishlistRemove::prepareRequest() method due to a null value being passed as the $product argument. When a product is removed from the wishlist, the Event object does not contain data about the product. Instead, the event provides a Magento\Wishlist\Model\Item object, which contains a reference to the associated product. By referencing the Item object in the event, the product is correctly retrieved, preventing the TypeError.

Error message: .CRITICAL: TypeError: Synerise\Integration\SyneriseApi\Mapper\Event\WishlistRemove::prepareRequest(): Argument https://github.com/Synerise/magento2-integration/pull/3 ($product) must be of type Magento\Catalog\Model\Product, null given

PR fix link: https://github.com/Synerise/magento2-integration/pull/82

**Comment by hellward** [comment]
Thank you for your report. The issue got addressed in [v3.0.8](https://github.com/Synerise/magento2-integration/releases/tag/v3.0.8)
